# Generated by Django 4.1.7 on 2023-03-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schooldata',
            old_name='school_user',
            new_name='school_username',
        ),
    ]
